mdenet/educationplatform

package-lock.json, platform/Dockerfile, platform/package.json, platform/public/common/utility.json, platform/src/Playground.js, platform/src/ToolsManager.js
Moved common utilities into the educationplatform static. 
Updated npm build script to copy files to the dist folder to simplify deployment.
=> Moved common utilities into the educationplatform static

platform/public/index.html, platform/src/Playground.js
Hide the login box by default and only show it when a private repo is given. This prevents the login box's brief display when loading a private repo mdenet/educationplatform-docker#2.
=> Hide the login box by default and only show for private repo

platform/src/Playground.js
Clear notifications for activities on handling a response and added cross icon to notifications to indicate that they can be closed.
To fix - https://github.com/mdenet/educationplatform/issues/98
=> Clear notifications for activities on handling a response and added icon

platform/src/Playground.js
The url encoding and puml changes from #105 that make the url displayed by the browser easy to reuse by copy and paste. Fix to puml handling and removed unused variable for OutputPanel creation.
=> YAMTL playground: url encoding puml 

platform/schemas/action.schema.json, platform/src/ActivityManager.js, platform/src/Playground.js
To support simultaneous display of output from toolfunction as well as another output type, added optional outputConsole in config file actions panel mapping so that a console panel can be specified. Removed outdated todo for handling language workbench editor.
Updated documentation mdenet/educationplatform.wiki@e0e1d4552fd147cf5d2f32b1229e8c7880f38a7b on branch `80-output-from-a-tool-function-is-not-displayed-in-a-console-panel`.
=> Added support for the display of tool console output and output

platform/src/ModelPanel.js
Fix for #122 in ModelPanel to use the panel's actual height so the diagrams are centred correctly and not hidden. Also removed some old commented out code.
=> Fix for hidden large diagrams

platform/src/Playground.js
Closes https://github.com/mdenet/platformtools/issues/25
=> Ensure Xtext editors are initialised from file if one is specified

platform/Dockerfile, platform/package.json, platform/src/Playground.js, platform/webpack.config.js
I have started to look into deploying a public instance of the platform. From what I can see, it seems like the token server URL was hardcoded into the JavaScript code:
```js
const TOKEN_HANDLER_URL = "http://127.0.0.1:10000";
```
This pull request allows for customising the URL of the token handler, by using a Webpack `DefinePlugin`. The line can be changed to:
```js
const TOKEN_HANDLER_URL = TOKEN_SERVER_URL || "http://127.0.0.1:10000";
```
The TOKEN_SERVER_URL value will be replaced on the fly by Webpack using the DefinePlugin. This would allow us to tweak the URL by using the appropriate value when calling `npm`, like this:
```shell
npm run build -- --env tokenServerUrl=http://foo:1234
```
I had to separate the `copyfiles` invocation into its own `npm run package` script, as otherwise …
=> Add support for customising the URL to the token server

platform/src/OutputPanel.js
I have a more in-depth example for the "Dev" side of the Annual Symposium tutorial, involving EGX. The EGX tool function returns a JSON with potentially multiple generated files, like this:
```json
{
"generatedFiles": [
{
"path": "../gradle/lib/src/main/java/org/mdenet/HelloWorld.java",
"content": "package org.mdenet;\n\npublic class HelloWorld {\n}\n"
}
]
}
```
The problem is that showing this correctly requires implementing the multiple-output support that got dropped during the refactoring from the Epsilon Playground to the MDENet EP. 
This PR adds it back for any panel definition that uses `multi` as its `language`, like this one:
```json
{
"id": "multicode",
"name": "code",
"panelclass": "OutputPanel",
"icon": "editor",
"language": "multi"
}
```
The panel definition would need to be …
=> Add support for multifile output

platform/public/css/custom.css, platform/public/index.html, platform/src/Playground.js
Fixes #130 
This pull request adds the CSS class `hidden` (whose display value is now `!important`) to the Save button, and tweaks the code that handles the event when we authenticate to GitHub to remove that class, so the Save button is shown.
=> Only show 'Save' button when authenticated

platform/src/Panel.js, platform/src/Playground.js, platform/src/ProgramPanel.js, platform/src/XtextEditorPanel.js
=> Save contents of generated Xtext editors, too

platform/src/ConsolePanel.js
This doesn't allow the user to lock in on a particular position, but it's better than not scrolling at all.
=> Make console always scroll to bottom on updates

platform/src/ActivityManager.js, platform/src/FileHandler.js, platform/src/ProgramPanel.js, platform/src/XtextEditorPanel.js
This PR adds support for interpolation in panel URLs in the activity specification.
This is useful to allow dependent activities to access information from other activities. The concrete motivating example was the generation of Xtext editors, where I may wish to allow students to access the meta-model generated by Xtext in the activity where they can try out their new language. The URL to that file is generated by the platform (specifically, the xtext tool) and so isn't known at the time when the activity specification file is written.
With this PR, I can now write something like:
```
{
"id": "panel-mm",
"name": "The meta-model generated by Xtext",
"ref": "ecore",
"file": "{{ID-panel-turtles}}/xtext-resources/generated/meta-model.ecore"
},
```
and have `{{ID-panel-turtles}}` replaced from …
=> Add support for URL interpolation when setting up panels

platform/src/Playground.js
A typo in the conversion code meant we weren't passing the actual panel contents to the conversion function.
=> For metamodel-free conversion, ensure we're converting the correct value

platform/schemas/paneldef.schema.json, platform/schemas/tool-config.schema.json
This PR fixes several issues in the tool configuration schemas to ensure these are correctly validated.
=> Fix tool config schemas

platform/src/ActivityManager.js
This means that tools can be generated on the fly if needed, for example for Xtext.
=> Allow URL interpolation in tool URLs

platform/src/ActivityManager.js, platform/src/ToolsManager.js
This PR adds support for tool specifications to use `{{BASE-URL}}` to refer to the URL from which the tool is deployed (strictly, the URL where the tool specification is hosted, minus the file name of the tool specification and any trailing `/`). This will automatically be rewritten when the tool specification is loaded, so that tool specifications can be written independently of location of deployment.
=> Add support for URL rewriting in tool specifications

platform/src/ActivityManager.js
This PR fixes a bug introduced by #161. Because tools with URL-rewriting in the tool URL may not be loaded unless they have been generated, any panels provided by them can also not be loaded unless the tool has been generated. As a result, checking if a panel is a generated panel cannot rely on the panel definition in these cases. Before this fix, activities with such panels would be shown in the activities menu regardless of whether generation has taken place.
To fix this, we assume that all panels with undefined panel definitions are generated and hide the corresponding activities in the menu. This also has the nice side effect that only activities with fully defined panels are visible in the menu.
=> Fix hiding of generated activities

platform/src/Playground.js
Provide a notification on editor builds failing for https://github.com/mdenet/platformtools/issues/39#issuecomment-1900066163
=> Provide a notification on editor builds failing 

platform/public/index.html, platform/public/js/cookieconsent-config.js
Added cookie consent box to indicate the cookies used by the platform. When deploying the platform the
PLATFORM_DEPLOY_DOMAIN should be set to the domain used for deployment.
=> Added cookie consent box to indicate the cookies used by the platform.

platform/src/Playground.js
This PR fixes a bug where the platform crashed when an action parameter wasn't actually a string
=> Do not assume action parameters are strings

platform/src/FileHandler.js, platform/src/Utility.js
This PR fixes some issues with encoding / decoding of UTF-8, especially in relation to Base64 (see also https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem for explanation of the problem). This is important, for example, because Xtend code uses guillemets which are only available in UTF-8, not plain ASCII.
=> Fix UTF-8 decoding errors

platform/src/FileHandler.js
Use utf8 encoding when saving panel contents to support non-ascii characters.
=> Fix utf8 encoding on save

platform/schemas/panel.schema.json, platform/schemas/ref.schema.json, platform/src/Playground.js
Fix for missing panel buttons. Panel definitions are required to resolve any button references given in an activity config file. Button references are identified by their type that is string rather than object for Buttons.
=> Fix for missing panel buttons

platform/src/ActivityConfigValidator.js
Fix for error caused by the new schema files from https://github.com/mdenet/educationplatform/pull/171 not being added to ActivityConfigValidator initialisation.
=> Added missing schema files to the ActivityConfigValidator

platform/src/Playground.js
This PR adds code to report all errors on playground startup.
Previous code only reported configuration errors and platform errors, using a specific format, but did not provide a catch-all section reporting any other errors that might occur. This now adds this catch-all block, which will report, for example, parsing errors and errors opening the activitiy file (which closes #128).
=> Report all errors on playground start up

platform/src/Playground.js
This PR fixes a problem where activity-defined buttons would only be shown if there were any buttons defined in the panel definition, too.
=> Resolve activity buttons without tool buttons

platform/src/ActivityManager.js, tokenserver/src/middleware/ErrorHandlingMiddleware.js
This PR fixes a problem whereby accessing a non-existing activities.json or a file where the permissions were missing would not lead to an error being reported to the user but would quietly crash the token server and the platform.
In the PR, the token server correctly reports the issue and the platform correctly raises an error to the user rather than trying to process the activity specification.
=> Correctly report activity access issues

tokenserver/src/controller/StorageController.js
This PR fixes the token server so that it correctly uses the provided `ref` parameter when loading files from GitHub.
=> Correctly use ref when loading files via token server

.github/workflows/ci.yml, package-lock.json, platform/.eslintignore, platform/.eslintrc.js, platform/package.json, platform/src/ActivityManager.js, platform/src/ConsolePanel.js, platform/src/FileHandler.js, platform/src/Layout.js, platform/src/OutputPanel.js, platform/src/Panel.js, platform/src/Playground.js, platform/src/ToolConfigUtility.js, platform/src/ToolsManager.js, platform/src/XtextEditorPanel.js, tokenserver/.eslintignore, tokenserver/.eslintrc.js, tokenserver/package.json, tokenserver/src/config.js, tokenserver/src/controller/LoginController.js, tokenserver/src/controller/StorageController.js, tokenserver/src/cookieName.js, tokenserver/src/middleware/ErrorHandlingMiddleware.js, tokenserver/src/server.js
Enabled linting for the education platform code. This is automatically run locally by vscode and the linter is  configure to run as part of GitHub action on pushing to a repository. A separate lint report is created similar to the unit test report.  
Part of mdenet/educationplatform#174
=> Enabled linting

platform/src/ActivityManager.js, platform/src/Playground.js, platform/src/Utility.js, platform/test/resources/TestActivityFiles.js, platform/test/resources/TestToolFiles.js, platform/test/resources/TestUtility.js, platform/test/spec/testActivityManagerSpec.js
Some unit tests for ActivityManager.
A couple of minor changes were required for test-ability:
- Calls to global browser objects `document` and `window` should be via utility functions that can be stubbed.
- Imports have to be via objects and not direct export.  This is because ES6 protects exports which prevents them being spied on by Jasmine. It is a problem for all javascript test frameworks.
- ActivityManager constructor made costly http requests so these were separated out into initializeActivities() method that's called after it's created.
Code coverage for the module at approx 52%
=> Unit tests for ActivityManager

package-lock.json, platform/package.json, platform/src/ToolsManager.js, platform/test/spec/testToolManagerSpec.js
Unit tests for ToolManager: constructor, initialisation, and getting grammar imports.
Updated comment in ToolsManager to reflect the actual returned type.
Added jasmine-ajax to development dependencies to enable testing of calls to `XMLHttpRequest`.
Code coverage for the module 72%.
=> Unit tests for ToolManager

platform/test/resources/TestActivityFiles.js, platform/test/resources/TestUtility.js, platform/test/spec/testActivityConfigValidatorSpec.js, platform/test/spec/testToolConfigValidatorSpec.js
Tests for ToolConfigValidator and ActivityConfigValidator.
Code coverage for the modules 100% though further tests can be added to check the contents of each error message against the error raised.
=> Tests for config validators

platform/src/EducationPlatformApp.js, platform/test/spec/testEducationPlatformAppSpec.js
Modified invokeActionFunction() to not populate unused parameters as 'undefined' because this is no longer necessary when using the Epsilon micronaut tool service.
Along https://github.com/epsilonlabs/playground-micronaut/pull/4 with fixes #41 
Mentioned in code review for PR https://github.com/mdenet/educationplatform/pull/198#discussion_r1531961177
=> Fix only provide parameters used by tool functions

platform/src/ActivityValidator.js, platform/test/spec/testActivityValidatorSpec.js
Unit tests for the ActivityValidator and minor modification to export error constants so they could be used in the tests.
> **Note** https://github.com/mdenet/educationplatform/pull/189 should be merged first
I considered loading configuration files rather than reconstructing minimal test activity and tool objects that was done in these tests but it meant relying on the ActivityManager and ToolManager and become too much of an integration test. 
Code coverage for the module is 100%
=> Tests for ActivityValidator

platform/src/EducationPlatformApp.js, platform/src/Layout.js
Fixed creation of panel splitters in Layout so that panel layouts with an odd number of panels do not have an unnecessary splitter that causes a Metro exception on page resize, and added defensive check for fit() when no splitters are found.
=> Fix errors on resize
